name: jcclass
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.5
  - pip
  - numpy>=1.19.5
  - matplotlib
  - xarray
  - pyproj
  - cartopy=0.18.0
  - cftime
  - netCDF4
  - h5netcdf

  #- pip:
#    - git+https://github.com/bashtage/sphinx-material.git
    #- jcclass
